/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientenverwaltung;

import java.awt.event.MouseEvent;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.geometry.Orientation;
import javax.swing.DefaultListModel;
import javax.swing.JProgressBar;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author tom.pauly
 */
public class Arztpraxis extends javax.swing.JFrame {

    private transient DefaultListModel listmodel;
    private transient String name;
    private transient int Selected = 0;
    private Queue<Patient> patienten = new Queue<>();
    /**
     * Creates new form PatientenGUI
     */
    public Arztpraxis() {
        //try {
            initComponents();
            
            jProgressBar1.setVisible(false);
            jProgressBar2.setVisible(false);
            
            jProgressBar1.setIndeterminate(true);
            jProgressBar2.setIndeterminate(true);
            listmodel = new DefaultListModel();
            List<String> temp = new ArrayList<>();
            
            Queue<Patient> temppatienten = patienten;
            while(temppatienten.front() != null){
                Patient patienten1 = temppatienten.front();
                temp.add(patienten1.getVorname() + " " + patienten1.getName());
                temppatienten.dequeue();
            }
            
            
            java.util.Collections.sort(temp);
            temp.stream().forEach((patient) -> {
                listmodel.addElement(patient);
            });
            jListAllerg.setModel(new DefaultListModel());
            jList1.setModel(listmodel);
            jTfN.setText(" ");
            jTfVn.setText(" ");
            jTfBg.setText(" ");
            jTfNn.setText(" ");
            new ThreadDemo("Thread", this.jProgressBar1, this.jProgressBar2).start();
            //this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        //} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            //Logger.getLogger(Arztpraxis.class.getName()).log(Level.SEVERE, null, ex);
        //}
    }
    public static void main(String[] args){
        Arztpraxis praxis = new Arztpraxis();
        praxis.setVisible(true);
    }
    
    public void Update(){
        int at = jList1.getSelectedIndex();
        listmodel = new DefaultListModel();
        List<String> temp = new ArrayList<>();
        for(int i = 0; i < GetLength(); i++){
            Patient tempPatient = AtIndex(i);
            temp.add(tempPatient.getVorname() + " " + tempPatient.getName());
        }
        java.util.Collections.sort(temp);
        temp.stream().forEach((patient) -> {
            listmodel.addElement(patient);
        });
        jList1.setModel(listmodel);
        jList1.setSelectedIndex(at);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListAllerg = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jTfVn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTfN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTfNn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTfBg = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTfAll = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTfOEdit = new javax.swing.JTextField();
        jTfPlEdit = new javax.swing.JTextField();
        jTfRnEdit = new javax.swing.JTextField();
        jTfStEdit = new javax.swing.JTextField();
        jTfHnEdit = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();
        jButton8 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jLabel2.setText("jLabel1");

        jLabel4.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jList1.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jListAllerg.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jListAllerg.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListAllerg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAllergMouseClicked(evt);
            }
        });
        jListAllerg.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListAllergValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListAllerg);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patientenverwaltung/Icons/ic_add_circle_black_18dp_2x.png"))); // NOI18N
        jButton1.setText("  Patient hinzufügen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTfVn.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel1.setText("Vorname:");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel3.setText("Name:");

        jTfN.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel5.setText("Notfallnummer:");

        jTfNn.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel6.setText("Blutgruppe:");

        jTfBg.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patientenverwaltung/Icons/ic_keyboard_arrow_down_black_18dp.png"))); // NOI18N
        jButton2.setText("  Vorwärts!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patientenverwaltung/Icons/ic_keyboard_arrow_up_black_18dp.png"))); // NOI18N
        jButton3.setText("Rückwärts!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patientenverwaltung/Icons/ic_create_new_folder_black_18dp.png"))); // NOI18N
        jButton4.setText("Allergie hinzufügen");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTfAll.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        jTfAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfAllActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patientenverwaltung/Icons/ic_keyboard_arrow_down_black_18dp.png"))); // NOI18N
        jButton5.setText("Vorwärts!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patientenverwaltung/Icons/ic_keyboard_arrow_up_black_18dp.png"))); // NOI18N
        jButton6.setText("Rückwärts!");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel7.setText("Ort:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel8.setText("Postleitzahl:");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel9.setText("Rufnummer:");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel10.setText("Straße:");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel11.setText("Hausnummer:");

        jTfOEdit.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N

        jTfPlEdit.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N

        jTfRnEdit.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        jTfRnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfRnEditActionPerformed(evt);
            }
        });

        jTfStEdit.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N

        jTfHnEdit.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patientenverwaltung/Icons/ic_autorenew_black_18dp.png"))); // NOI18N
        jButton7.setText("Patient aktualisieren");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patientenverwaltung/Icons/ic_backup_black_48dp.png"))); // NOI18N
        jButton9.setText("LADEN");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jButton10.setText("Neuer Patient");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jProgressBar1.setBackground(new java.awt.Color(255, 102, 255));
        jProgressBar1.setForeground(new java.awt.Color(255, 0, 0));
        jProgressBar1.setFocusCycleRoot(true);

        jProgressBar2.setBackground(new java.awt.Color(255, 102, 255));
        jProgressBar2.setForeground(new java.awt.Color(255, 0, 0));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patientenverwaltung/Icons/ic_search_black_18dp_2x.png"))); // NOI18N
        jButton8.setText("Suchen");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTfAll)
                                    .addComponent(jButton6)
                                    .addComponent(jButton5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTfN, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTfNn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTfBg, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTfOEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTfPlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTfRnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTfStEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTfHnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTfVn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2)
                                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(jTfVn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTfN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTfNn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTfBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTfOEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTfPlEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTfRnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTfStEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTfHnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(200, 200, 200)
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTfAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)))
                                .addGap(51, 51, 51)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        ValueChangedInJList1();
    }//GEN-LAST:event_jList1ValueChanged

    private void ValueChangedInJList1(){
        if(jList1.getSelectedIndex() != -1){
            DefaultListModel newListModel = new DefaultListModel();
            int sel = jList1.getSelectedIndex();
            Patient temp = AtIndex(sel);
            this.jTfBg.setText(temp.getBlutgruppe());
            this.jTfNn.setText(temp.getNotfallnummer());
            this.jTfHnEdit.setText(temp.getHausnummer());
            this.jTfOEdit.setText(temp.getOrt());
            this.jTfPlEdit.setText(temp.getPlz());
            this.jTfRnEdit.setText(temp.getRufnummer());
            this.jTfStEdit.setText(temp.getStrasse());
            this.jTfN.setText(temp.getName());
            this.jTfVn.setText(temp.getVorname());
            int counter = 0;
            while(counter <= temp.GetAllergienLength() - 1){
                newListModel.addElement(temp.AtIndexAllergie(counter));
                counter++;
            }
            jListAllerg.setModel(newListModel);
        }
        else{
            this.jTfBg.setText("");
            this.jTfNn.setText("");
            this.jTfHnEdit.setText("");
            this.jTfOEdit.setText("");
            this.jTfPlEdit.setText("");
            this.jTfRnEdit.setText("");
            this.jTfStEdit.setText("");
            this.jTfVn.setText("");
            this.jTfN.setText("");
            jListAllerg.setModel(new DefaultListModel());
        }
    }
    
    
    private void RemovePatient(int index){
        int counter = 0;
        Queue<Patient> temp = new Queue<>();
        while(patienten.front() != null){
            
            if(counter == index){
                patienten.dequeue();
            }
            else{
                temp.enqueue(patienten.front());
                patienten.dequeue();
            }
            counter++;
        }
        patienten = temp;
    }
    
    private Patient AtIndex(int index){
        Patient finnal = null;
        Patient temp = patienten.front();
        Queue<Patient> temmp = new Queue<>();
        int counter = 0;
        while(temp != null){
            if(counter == index){
                finnal = temp;
            }
            temmp.enqueue(temp);
            patienten.dequeue();
            temp = patienten.front();
            counter++;
        }
        while(temmp.front() != null){
            patienten.enqueue(temmp.front());
            temmp.dequeue();
        }
        return finnal;
    }
    
    private int IndexOf(Patient meinPatient){
        int counter = 0;
        boolean addToCounter =true;
        Patient temp = patienten.front();
        Queue<Patient> tempQueue = new Queue<>();
        while(temp != null){
            if(temp.equals(meinPatient)){
                addToCounter = false;
            }
            if(addToCounter){
                counter++;
            }
            tempQueue.enqueue(temp);
            patienten.dequeue();
            temp = patienten.front();
        }
        patienten = tempQueue;
        return counter;
    }
    
    private int GetLength(){
        Queue<Patient> temmp = new Queue<>();
        int counter = 0;
        while(patienten.front() != null){
            temmp.enqueue(patienten.front());
            patienten.dequeue();
            counter++;
        }
        while(temmp.front() != null){
            patienten.enqueue(temmp.front());
            temmp.dequeue();
        }
        return counter;
    }
    
    private void jListAllergMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAllergMouseClicked
        if(evt.getButton() == MouseEvent.BUTTON3){
            int something = jList1.getSelectedIndex();
            int somethingelse = jListAllerg.getSelectedIndex();
            Patient patient = AtIndex(something);
            jListAllerg.setSelectedIndex(-1);
            patient.RemoveAllergieAtIndex(somethingelse);
            jListAllerg.setSelectedIndex(-1);
            ValueChangedInJList1();
        }
        Speichern();
    }//GEN-LAST:event_jListAllergMouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if(evt.getButton() == MouseEvent.BUTTON3){
            int something = jList1.getSelectedIndex();
            jList1.setSelectedIndex(-1);
            this.RemovePatient(something);
            Update();
            jList1.setSelectedIndex(-1);
            ValueChangedInJList1();
            Speichern();
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jListAllergValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListAllergValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jListAllergValueChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(jList1.getComponentCount() != 0 && jList1.getSelectedIndex() != -1){
            Patient temp = AtIndex(jList1.getSelectedIndex());
            temp.getAllergien().enqueue(jTfAll.getText().trim());
            jTfAll.setText("");
            int sel = jList1.getSelectedIndex();
            DefaultListModel newListModel = new DefaultListModel();
            int counter = 0;
            while(counter <= temp.GetAllergienLength() - 1){
                newListModel.addElement(temp.AtIndexAllergie(counter));
                counter++;
            }
            jListAllerg.setModel(newListModel);
        }
        Speichern();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        switch (jListAllerg.getSelectedIndex()) {
            case 0:
                jListAllerg.setSelectedIndex(jListAllerg.getModel().getSize() - 1);
                break;
            case -1:
                jListAllerg.setSelectedIndex(0);
                break;
            default:
                jListAllerg.setSelectedIndex(jListAllerg.getSelectedIndex() - 1);
                break;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(jListAllerg.getSelectedIndex() != -1){
            Patient temp = AtIndex(jList1.getSelectedIndex());
            if(!"".equals(temp.AtIndexAllergie(jListAllerg.getSelectedIndex() + 1)) && temp.AtIndexAllergie(jListAllerg.getSelectedIndex() + 1) != null && jListAllerg.getSelectedIndex() != -1){
                jListAllerg.setSelectedIndex(jListAllerg.getSelectedIndex() + 1);
            }
            else{
                jListAllerg.setSelectedIndex(0);
            }
        }
        else{
                jListAllerg.setSelectedIndex(0);
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int sel = jList1.getSelectedIndex();
        if(sel != -1){
            Patient temp = AtIndex(sel);
        temp.setBlutgruppe(jTfBg.getText());
        temp.setHausnummer(jTfHnEdit.getText());
        temp.setOrt(jTfOEdit.getText());
        temp.setPlz(jTfPlEdit.getText());
        temp.setRufnummer(jTfRnEdit.getText());
        temp.setNotfallnummer(jTfNn.getText());
        temp.setStrasse(jTfStEdit.getText());
        temp.setName(jTfN.getText());
        temp.setVorname(jTfVn.getText());
        try {
                FileOutputStream fos = new FileOutputStream("liste.dat");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(patienten);
            } catch ( IOException e ) {
            }
        Update();
        Speichern();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.jTfBg.setText("");
            this.jTfNn.setText("");
            this.jTfHnEdit.setText("");
            this.jTfOEdit.setText("");
            this.jTfPlEdit.setText("");
            this.jTfRnEdit.setText("");
            this.jTfStEdit.setText("");
            this.jTfVn.setText("");
            this.jTfN.setText("");
            jListAllerg.setModel(new DefaultListModel());
    }//GEN-LAST:event_jButton10ActionPerformed

    public boolean isAlpha(String name) {
        if(name.isEmpty()){
            return false;
        }
    return name.matches("[a-zA-Z]+");
}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(isAlpha(jTfN.getText().trim()) || isAlpha(jTfVn.getText().trim())){
            Patient patient = new Patient((jTfN.getText().trim()), (jTfVn.getText().trim()));
            patient.setBlutgruppe((jTfBg.getText().trim()));
            patient.setNotfallnummer((jTfNn.getText().trim()));
            patient.setOrt(jTfOEdit.getText());
            patient.setPlz(jTfPlEdit.getText());
            patient.setRufnummer(jTfRnEdit.getText());
            patient.setStrasse(jTfStEdit.getText());
            patient.setHausnummer(jTfHnEdit.getText());
            patienten.enqueue(patient);
            Update();
        }
        /*
        this.jTfBg.setText("");
            this.jTfNn.setText("");
            this.jTfHnEdit.setText("");
            this.jTfN.setText("");
            this.jTfOEdit.setText("");
            this.jTfPlEdit.setText("");
            this.jTfRnEdit.setText("");
            this.jTfStEdit.setText("");
            this.jTfVn.setText("");
            this.jTfN.setText("");
                */
        Speichern();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void Speichern(){
        try {
            if(patienten != null && patienten.front() != null){
                FileOutputStream fos = new FileOutputStream("liste.dat");
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(patienten);
            }
            } catch ( IOException e ) {
           
            }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(AtIndex(jList1.getSelectedIndex() +1) != null){
            jList1.setSelectedIndex(jList1.getSelectedIndex() + 1);
        }
        else{
            jList1.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        switch (jList1.getSelectedIndex()) {
            case 0:
                jList1.setSelectedIndex(jList1.getModel().getSize() - 1);
                break;
            case -1:
                jList1.setSelectedIndex(0);
                break;
            default:
                jList1.setSelectedIndex(jList1.getSelectedIndex() - 1);
                break;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        try {
        FileInputStream file = new FileInputStream("liste.dat");
            try (ObjectInputStream o = new ObjectInputStream(file)) {
                patienten = (Queue<Patient>) o.readObject();
            }
        } catch ( IOException | ClassNotFoundException e ) {
        }
            Update();  
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTfAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfAllActionPerformed

    private void jTfRnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfRnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfRnEditActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(isAlpha(jTextField1.getText())){
            Queue<Patient> temppatienten = new Queue<>();
            while(patienten.front() != null){
                Patient patienten1 = patienten.front();
                if(patienten1.getName().contains(jTextField1.getText())){
                    jList1.setSelectedIndex(IndexOf(patienten1));
                }
                temppatienten.enqueue(patienten1);
                patienten.dequeue();
            }
            patienten = temppatienten;
        }
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jListAllerg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTfAll;
    private javax.swing.JTextField jTfBg;
    private javax.swing.JTextField jTfHnEdit;
    private javax.swing.JTextField jTfN;
    private javax.swing.JTextField jTfNn;
    private javax.swing.JTextField jTfOEdit;
    private javax.swing.JTextField jTfPlEdit;
    private javax.swing.JTextField jTfRnEdit;
    private javax.swing.JTextField jTfStEdit;
    private javax.swing.JTextField jTfVn;
    // End of variables declaration//GEN-END:variables
}

class ThreadDemo extends Thread {
   private Thread t;
   private final String threadName;
   private final JProgressBar jpb1;
   private final JProgressBar jpb2;
   
   ThreadDemo(String name, JProgressBar jpb1, JProgressBar jpb2){
       this.jpb1 = jpb1;
       this.jpb2 = jpb2;
       threadName = name;
       System.out.println("Creating " +  threadName );
   }
   @Override
   public void run() {
      while(true){
          jpb1.setOrientation(Orientation.VERTICAL.ordinal());
          jpb2.setOrientation(Orientation.HORIZONTAL.ordinal());
          //jpb1.setVisible(!jpb1.isVisible());
          //jpb2.setVisible(!jpb2.isVisible());
          try{
              Thread.sleep(100);
          } catch(Exception ex){
              
          }
          jpb1.setOrientation(Orientation.HORIZONTAL.ordinal());
          jpb2.setOrientation(Orientation.VERTICAL.ordinal());
          //jpb1.setVisible(!jpb1.isVisible());
          //jpb2.setVisible(!jpb2.isVisible());
          try{
              Thread.sleep(100);
          } catch(Exception ex){
              
          }
      }
   }
   
   @Override
   public void start ()
   {
      System.out.println("Starting " +  threadName );
      if (t == null)
      {
         t = new Thread (this, threadName);
         t.start ();
      }
   }

}


